sudo: required
services:
  - docker

before_install:
  - docker build -t carlosz/docker-workflow -f frontend/Dockerfile.dev frontend/

script:
  - docker run carlosz/docker-workflow npm run test -- --coverage